spring:
  application:
    name: microservice-logging

  activemq:
    broker-url: tcp://172.17.0.1:61616
    user: myuser
    password: mypwd

server:
  port: 8086


message:
  file: /var/message.log