name: Build Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build microservice-chat image
        run: |
          docker build -t theoahga/microservice-chat:1.0 ./microservice-chat

      - name: Build microservice-game image
        run: |
          docker build -t theoahga/microservice-game:1.0 ./microservice-game

      - name: Build microservice-logging image
        run: |
          docker build -t theoahga/microservice-logging:1.0 ./microservice-logging

      - name: Build microservice-websocket image
        run: |
          docker build -t theoahga/microservice-websocket:1.0 ./microservice-websocket

      - name: Push microservice-chat image
        run: |
          docker push theoahga/microservice-chat:1.0

      - name: Push microservice-game image
        run: |
          docker push theoahga/microservice-game:1.0

      - name: Push microservice-logging image
        run: |
          docker push theoahga/microservice-logging:1.0

      - name: Push microservice-websocket image
        run: |
          docker push theoahga/microservice-websocket:1.0
